name: ipl4eo
channels:
  # PyTorch channel *must* be the first channel otherwise CPU from conda-forge is used
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.3
  - numpy>=1.22
  - sentinelsat=1
  - jupyter=1
  - notebook
  - pydantic=1
  - dynaconf
  # updating geopandas or rasterio should
  # be done deliberately and tested!
  - matplotlib
  - geopandas==1.0.1
  - rasterio==1.4.3
  - osmnx
  - seaborn
  - easydict
  - scikit-learn
  - spectral
  # taking values from:
  # https://pytorch.org/get-started/previous-versions/
  - pytorch==2.5.1
  - torchvision==0.20.1
  - torchaudio==2.5.1
  # Only install the following for linux-64!
  - pytorch-cuda=11.8 # [linux]
  # If we only want to use the CPU only variant
  # - cpuonly
  - torchinfo
  - visdom
  - openpyxl
  - ipywidgets
  - jupyterlab_widgets
  - jupyterlab
  - black
  - isort
  - flake8
  - pytest
  # - pre-commit <- Let's keep it separat for now
  - pip
  - requests
  - rich
  - tqdm
  - tensorboard
  - pytorch-lightning
  - libgdal-jp2openjpeg
# for conda-lock
platforms:
  - osx-64
  - osx-arm64
  - linux-64

